version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/healthcare_db
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://roundhouse.proxy.rlwy.net:5432/railway
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=JJJLpikiApddeCJGTnfnMVwslBTxeluo
      - JWT_SECRET=healthcare-jwt-secret-key-256-bit-minimum!!
    extra_hosts:
      - "host.docker.internal:host-gateway"